extends Node
class_name Constants

const SCREEN_MANAGEMENT = "management"
const SCREEN_MONSTER = "monster"
const SCREEN_COMBAT = "combat"
const SCREEN_RESULT = "result"
const SCREEN_ENDING = "ending"
const SCREEN_ENDING_ARCHIVE = "ending_archive"
const SCREEN_MEMORY_ARCHIVE = "memory_archive"
const SCREEN_CYCLE_DOCTRINE = "cycle_doctrine"
const SCREEN_CYCLE_DECREE = "cycle_decree"
const SCREEN_CHALLENGE_SEAL = "challenge_seal"
const SCREEN_CONTRACT_BOARD = "contract_board"
const SCREEN_FRONT_SELECTION = "front_selection"
const SCREEN_CAMPAIGN_MODE = "campaign_mode_selection"
const SCREEN_REGION_SELECTION = "region_selection"
const SCREEN_OUTPOST_MANAGEMENT = "outpost_management"
const SCREEN_OUTPOST_BATTLE = "outpost_battle"
const SCREEN_UPPER_FLOOR = "upper_floor"
const SCREEN_HEART_SELECTION = "heart_selection"
const SCREEN_DUO_LINK_LOADOUT = "duo_link_loadout"
const SCREEN_CHRONICLE = "chronicle"
const SCREEN_TITLE = "title"
const SCREEN_NAME_ENTRY = "name_entry"
const SCREEN_DIALOGUE = "dialogue"
const SCREEN_RAID_PREVIEW = "raid_preview"
const SCREEN_RAID = "raid"
const SCREEN_SETTINGS = "settings"

const FACTION_MONSTER = "monster"
const FACTION_ENEMY = "enemy"

const DIRECTIVE_DEFENSE = "defense"
const DIRECTIVE_ALL_OUT = "all_out"
const DIRECTIVE_SURVIVAL = "survival"

const ROOM_DIRECTIVE_NONE = "none"
const ROOM_DIRECTIVE_ENTRY_BLOCK = "entry_block"
const ROOM_DIRECTIVE_TRAP_LURE = "trap_lure"
const ROOM_DIRECTIVE_RETREAT = "retreat"

const ACTIVITY_EXP_CAP = 7

const UNIT_STATE_IDLE = "idle"
const UNIT_STATE_MOVE_TO_ROOM = "move_to_room"
const UNIT_STATE_SEEK_TARGET = "seek_target"
const UNIT_STATE_MOVE_TO_TARGET = "move_to_target"
const UNIT_STATE_ATTACK = "attack"
const UNIT_STATE_CAST_SKILL = "cast_skill"
const UNIT_STATE_RETREAT = "retreat"
const UNIT_STATE_STUNNED = "stunned"
const UNIT_STATE_LOOTING = "looting"
const UNIT_STATE_DOWN = "down"

